### ISSUE TITLE
Add a button for a fixed duration task

### ISSUE THREAD

**Issue by shervinemami** [hackaru-app/hackaru#20]
Hi, I'd love if Hackaru includes a button that simply allows the duration to be set to an exact length, say 1 hour. I want to compare how often I have been performing tasks, so that I can see the count, not the duration. eg: I want to see that I did coding 5 times this week and exercise 3 times. Knowing this count is more important to me than knowing that I was coding was 8 hours and exercising for 2 hours. When starting the timer for a task, if you included a button that says "Perform 1 hour" or something like that, then it can be achieved without changing anything else in the project :-)

So if you can please add this feature, I would be very grateful!

**Comment by ktmouk** [comment]
Hello, thank you very much for your feedback!

Your feedback is very informative, but at this point we are unable to make a decision to add that feature.
Basically, this is a time tracking app, but not a habit tracking app to see the count.

However, if we receive many requests from users, we will consider adding this feature.
