### ISSUE TITLE
月曜始まり〜日曜終わりに切り替えられる機能が欲しい

### ISSUE THREAD

**Issue by momeemt** [hackaru-app/hackaru#21]
## Is your feature request related to a problem? Please describe.
私は複数のカレンダーアプリにおいて、月曜始まり〜日曜終わりに慣れ親しんでいます。
Hackaruのタイムラインに若干違和感を感じていました。

## Describe the solution you'd like
週タイムライン / 週次レポートを月曜始まり〜日曜終わりに切り替えられる機能が欲しいです。

## Describe alternatives you've considered
詳細は特にありません。

**Comment by ktmouk** [comment]
@momeemt 
フィードバックありがとうございます。
週始まりを変更できるように改善しました！
