### ISSUE TITLE
APIによるCSVファイルダウンロード

### ISSUE THREAD

**Issue by Dahobr** [hackaru-app/hackaru#27]
Hackaru、非常に便利でいつも活用させていただいています！本当にありがとうございます！

さて表題にも書きましたが、公式サイトにて計測したデータをGoogleスプレッドシートからGASを使ってCSVファイルとしてダウンロードできればと考えています。バックではAPIを用いたRESTFulなやりとりがなされているようですが、一般ユーザーが用いるエンドポイントも用意されているのでしょうか？

全く無料で利用させていただいていてさらにお願い事をして申し訳ないですが、ご案内頂けましたら幸いです。

**Comment by ktmouk** [comment]
ご要望ありがとうございます!
現状、一般ユーザからRESTFul APIを叩く導線はありませんが、将来的にOAuth経由でAPIが呼び出せるようにする改修を計画していますので、しばしお待ちいただければと思います。:pray:
