### ISSUE TITLE
The future of hackaru as an open source project.

### ISSUE THREAD

**Issue by zhzy0077** [hackaru-app/hackaru#28]
It's so unfortunate that I just found this project and Hackaru as a cloud service is going to be discontinued.

However, as an open source project, will you continue to maintain this product and move it forward?

BTW: I sent several PRs to support:
- Simplified Chinese: https://github.com/hackaru-app/hackaru-api/pull/1675, https://github.com/hackaru-app/hackaru-web/pull/1319
- MySQL: https://github.com/hackaru-app/hackaru-api/pull/1670

**Comment by ktmouk** [comment]
Thank you for sending the issue and PRs!
Unfortunately, I'm not going to continue to maintain this project and I will archive these repositories after merging PRs you sent.
But I'm really glad you are interested in this product. Thank you.
